package github.detrig.feature.pet.presentation

/** Logical layer names share identical artwork across fur and ear variants. */
internal fun dirtAssetPath(source: String): String = DIRT_ASSET_ALIASES[source] ?: source

private val DIRT_ASSET_ALIASES = mapOf(
    "clothing/01_leaf_tee/main_fluffy.webp" to "clothing/01_leaf_tee/main_cheeks.webp",
    "clothing/01_leaf_tee/main_smooth.webp" to "clothing/01_leaf_tee/main_cheeks.webp",
    "clothing/01_leaf_tee/sleeve_left_smooth.webp" to "clothing/01_leaf_tee/sleeve_left_cheeks.webp",
    "clothing/01_leaf_tee/sleeve_right_smooth.webp" to "clothing/01_leaf_tee/sleeve_right_cheeks.webp",
    "clothing/02_sailor_tee/main_smooth.webp" to "clothing/02_sailor_tee/main_cheeks.webp",
    "clothing/02_sailor_tee/sleeve_left_smooth.webp" to "clothing/02_sailor_tee/sleeve_left_cheeks.webp",
    "clothing/02_sailor_tee/sleeve_right_smooth.webp" to "clothing/02_sailor_tee/sleeve_right_cheeks.webp",
    "clothing/03_lilac_hoodie/main_smooth.webp" to "clothing/03_lilac_hoodie/main_cheeks.webp",
    "clothing/03_lilac_hoodie/sleeve_left_smooth.webp" to "clothing/03_lilac_hoodie/sleeve_left_cheeks.webp",
    "clothing/03_lilac_hoodie/sleeve_right_smooth.webp" to "clothing/03_lilac_hoodie/sleeve_right_cheeks.webp",
    "clothing/04_yellow_raincoat/main_fluffy.webp" to "clothing/04_yellow_raincoat/main_cheeks.webp",
    "clothing/04_yellow_raincoat/main_smooth.webp" to "clothing/04_yellow_raincoat/main_cheeks.webp",
    "clothing/04_yellow_raincoat/sleeve_left_smooth.webp" to "clothing/04_yellow_raincoat/sleeve_left_cheeks.webp",
    "clothing/04_yellow_raincoat/sleeve_right_smooth.webp" to "clothing/04_yellow_raincoat/sleeve_right_cheeks.webp",
    "clothing/05_teal_cardigan/main_smooth.webp" to "clothing/05_teal_cardigan/main_cheeks.webp",
    "clothing/05_teal_cardigan/sleeve_left_fluffy.webp" to "clothing/05_teal_cardigan/sleeve_left_cheeks.webp",
    "clothing/05_teal_cardigan/sleeve_right_smooth.webp" to "clothing/05_teal_cardigan/sleeve_right_cheeks.webp",
    "clothing/06_denim_vest/main_fluffy.webp" to "clothing/06_denim_vest/main_cheeks.webp",
    "clothing/06_denim_vest/main_smooth.webp" to "clothing/06_denim_vest/main_cheeks.webp",
    "clothing/06_denim_vest/sleeve_left_smooth.webp" to "clothing/06_denim_vest/sleeve_left_cheeks.webp",
    "clothing/06_denim_vest/sleeve_right_smooth.webp" to "clothing/06_denim_vest/sleeve_right_cheeks.webp",
    "clothing/07_plaid_shirt/main_smooth.webp" to "clothing/07_plaid_shirt/main_cheeks.webp",
    "clothing/07_plaid_shirt/sleeve_left_smooth.webp" to "clothing/07_plaid_shirt/sleeve_left_cheeks.webp",
    "clothing/07_plaid_shirt/sleeve_right_smooth.webp" to "clothing/07_plaid_shirt/sleeve_right_cheeks.webp",
    "clothing/08_garden_overalls/main_fluffy.webp" to "clothing/08_garden_overalls/main_cheeks.webp",
    "clothing/08_garden_overalls/main_smooth.webp" to "clothing/08_garden_overalls/main_cheeks.webp",
    "clothing/08_garden_overalls/sleeve_left_smooth.webp" to "clothing/08_garden_overalls/sleeve_left_cheeks.webp",
    "clothing/08_garden_overalls/sleeve_right_smooth.webp" to "clothing/08_garden_overalls/sleeve_right_cheeks.webp",
    "clothing/09_cream_sweater/main_smooth.webp" to "clothing/09_cream_sweater/main_cheeks.webp",
    "clothing/09_cream_sweater/sleeve_left_smooth.webp" to "clothing/09_cream_sweater/sleeve_left_cheeks.webp",
    "clothing/09_cream_sweater/sleeve_right_smooth.webp" to "clothing/09_cream_sweater/sleeve_right_cheeks.webp",
    "clothing/10_coral_dress/main_fluffy.webp" to "clothing/10_coral_dress/main_cheeks.webp",
    "clothing/10_coral_dress/main_smooth.webp" to "clothing/10_coral_dress/main_cheeks.webp",
    "clothing/10_coral_dress/sleeve_left_smooth.webp" to "clothing/10_coral_dress/sleeve_left_cheeks.webp",
    "clothing/10_coral_dress/sleeve_right_smooth.webp" to "clothing/10_coral_dress/sleeve_right_cheeks.webp",
    "clothing/11_star_pajamas/main_fluffy.webp" to "clothing/11_star_pajamas/main_cheeks.webp",
    "clothing/11_star_pajamas/main_smooth.webp" to "clothing/11_star_pajamas/main_cheeks.webp",
    "clothing/11_star_pajamas/sleeve_left_smooth.webp" to "clothing/11_star_pajamas/sleeve_left_cheeks.webp",
    "clothing/11_star_pajamas/sleeve_right_smooth.webp" to "clothing/11_star_pajamas/sleeve_right_cheeks.webp",
    "clothing/12_plum_waistcoat/main_smooth.webp" to "clothing/12_plum_waistcoat/main_cheeks.webp",
    "clothing/12_plum_waistcoat/sleeve_left_smooth.webp" to "clothing/12_plum_waistcoat/sleeve_left_cheeks.webp",
    "clothing/12_plum_waistcoat/sleeve_right_smooth.webp" to "clothing/12_plum_waistcoat/sleeve_right_cheeks.webp",
    "clothing/14_blue_cap/main_round.webp" to "clothing/14_blue_cap/main_folded.webp",
    "clothing/21_cherry_bow/main_round.webp" to "clothing/21_cherry_bow/main_folded.webp",
    "clothing/21_cherry_bow/main_wide.webp" to "clothing/21_cherry_bow/main_folded.webp",
    "clothing/22_flower_wreath/main_round.webp" to "clothing/22_flower_wreath/main_folded.webp",
    "pet/body_smooth.webp" to "pet/body_cheeks.webp",
    "pet/ears_wide.webp" to "pet/ears_round.webp",
)
